import "dotenv/config";
// Phase 5 end-to-end test: drives the real HTTP routes against a real database. Run: TEST_DATABASE_URL=... npx ts-node tests/phase5.e2e.ts
process.env.PORT = "4100"; process.env.NODE_ENV = "development";
if (!/test/i.test(process.env.TEST_DATABASE_URL ?? "")) { console.error("Set TEST_DATABASE_URL to an EMPTY throwaway database whose name contains \"test\" (this script creates users and data)."); process.exit(2); }
process.env.DATABASE_URL = process.env.TEST_DATABASE_URL!;
process.env.DATA_ENC_KEY = "a".repeat(64);
import bcrypt from "bcryptjs";
import fs from "fs";
import { prisma } from "../src/lib/prisma";
import "../src/server";
import { runTokenJob } from "../src/jobs/tokens";

const B = "http://localhost:4100/api";
let pass = 0, fail = 0;
const ok = (c: any, m: string) => { if (c) { pass++; console.log("  ✓", m); } else { fail++; console.log("  ✗ FAIL:", m); } };
async function call(method: string, p: string, tok?: string, body?: any, form?: FormData) {
  const r = await fetch(B + p, { method, headers: { ...(tok ? { Authorization: "Bearer " + tok } : {}), ...(body ? { "Content-Type": "application/json" } : {}) }, body: form ?? (body ? JSON.stringify(body) : undefined) });
  const ct = r.headers.get("content-type") ?? "";
  return { s: r.status, j: ct.includes("json") ? await r.json() : null, buf: ct.includes("pdf") ? Buffer.from(await r.arrayBuffer()) : null };
}
async function reg(role: string, name: string, n: number) {
  const r = await call("POST", "/auth/register", undefined, { role, fullName: name, email: `${role.toLowerCase()}${n}@t.com`, phone: `0803000000${n}`, password: "Password123!" });
  if (r.s !== 201) throw new Error("register failed " + JSON.stringify(r.j));
  return { id: r.j.user.id as string, tok: r.j.accessToken as string };
}
const DAY = 86_400_000;

async function main() {
  await new Promise((r) => setTimeout(r, 1500));
  console.log("\n— SETUP");
  const owner = await reg("OWNER", "Chinedu Okafor", 1), mgr = await reg("MANAGER", "Ada Eze", 2), t1 = await reg("TENANT", "Ngozi Bello", 3), t2 = await reg("TENANT", "Tunde Ade", 4), stranger = await reg("OWNER", "Other Owner", 5);
  const admin = await prisma.user.create({ data: { role: "ADMIN", fullName: "Admin", email: "admin@t.com", phone: "08000000000", passwordHash: await bcrypt.hash("Password123!", 4), emailVerified: true, phoneVerified: true } });
  const adminTok = (await call("POST", "/auth/login", undefined, { email: "admin@t.com", password: "Password123!" })).j.accessToken;
  await prisma.kycRecord.create({ data: { userId: owner.id, idType: "NIN", idNumberHash: "h1", idDocumentUrl: "x", selfieUrl: "y", status: "VERIFIED" } });
  await prisma.kycRecord.create({ data: { userId: mgr.id, idType: "NIN", idNumberHash: "h2", idDocumentUrl: "x", selfieUrl: "y", status: "VERIFIED" } });
  const loc = await prisma.location.create({ data: { name: "Lagos", level: "STATE" } });
  const ut = await prisma.unitType.create({ data: { name: "Self-Contain" } });
  const tier = await prisma.onboardingFeeTier.create({ data: { name: "t", kind: "HOUSE", amountKobo: 1000 } });
  const prop = await prisma.property.create({ data: { kind: "BUILDING", name: "Palm Court", address: "1 Palm St", locationId: loc.id, ownerId: owner.id, status: "ACTIVE", declaredUnits: 10 } });
  await prisma.propertyOnboarding.create({ data: { propertyId: prop.id, tierId: tier.id, amountKobo: 1000, paidAt: new Date(), startsAt: new Date(), expiresAt: new Date(Date.now() + 300 * DAY), graceEndsAt: new Date(Date.now() + 314 * DAY) } });
  await prisma.managerAssignment.create({ data: { propertyId: prop.id, managerId: mgr.id, canApproveTokens: true, canReceivePayments: false } });
  const mkUnit = async (title: string, rent = 50_000_00) => prisma.unit.create({ data: { propertyId: prop.id, unitTypeId: ut.id, title, rentKobo: rent, cautionKobo: 5_000_00, serviceChargeKobo: 2_000_00, status: "AVAILABLE", images: { create: [1, 2, 3].map((i) => ({ url: `/media/a${i}.jpg`, sortOrder: i })) } } });
  const [uA, uB, uC, uD] = [await mkUnit("Unit A"), await mkUnit("Unit B"), await mkUnit("Unit C"), await mkUnit("Unit D")];
  const TOTAL = 57_000_00;

  console.log("\n— PAYEE ACCOUNTS");
  let r = await call("POST", "/accounts", owner.tok, { bankName: "GTBank", accountName: "OKAFOR CHINEDU", accountNumber: "0123456789" });
  ok(r.s === 201 && r.j.status === "APPROVED" && r.j.isDefault, "owner account with matching name is auto-approved and default");
  ok(!JSON.stringify(r.j).includes("0123456789"), "full account number is never returned in lists");
  r = await call("POST", "/accounts", owner.tok, { bankName: "Access", accountName: "Some Company Ltd", accountNumber: "0987654321" });
  ok(r.j.status === "PENDING_REVIEW", "mismatched account name goes to admin review");
  const pendingAcc = r.j.id;
  r = await call("POST", "/accounts", mgr.tok, { bankName: "GTBank", accountName: "Ada Eze", accountNumber: "0123456789" });
  ok(r.j.status === "PENDING_REVIEW", "same account number used by a different user is flagged");
  r = await call("POST", "/accounts", owner.tok, { bankName: "X", accountName: "Okafor Chinedu", accountNumber: "123" });
  ok(r.s === 400, "bad account number rejected");
  r = await call("GET", "/admin/accounts", adminTok);
  ok(r.j.length === 2 && r.j.some((a: any) => a.usedByOtherUsers === 1), "admin queue shows both with the shared-account flag");
  r = await call("POST", `/admin/accounts/${pendingAcc}/decision`, adminTok, { decision: "REJECTED" });
  ok(r.s === 400, "rejecting needs a reason");
  r = await call("POST", `/admin/accounts/${pendingAcc}/decision`, adminTok, { decision: "REJECTED", reason: "Name mismatch" });
  ok(r.s === 200, "admin can reject");
  r = await call("GET", `/admin/accounts/${pendingAcc}/reveal`, adminTok);
  ok(r.j.accountNumber === "0987654321", "admin can reveal the number");
  ok((await prisma.auditLog.count({ where: { action: "ACCOUNT_NUMBER_VIEWED" } })) === 1, "reveal is audited");

  console.log("\n— REQUESTING A TOKEN");
  ok(!(await prisma.user.findUnique({ where: { id: t1.id } }))!.phoneVerified, "test tenant has not verified a phone");
  r = await call("POST", "/tokens/request", t1.tok, { unitId: uA.id, note: "Hi" });
  ok(r.s === 201 && r.j.totalKobo === TOTAL, "tenant without phone verification can request a token; total = rent+caution+service");
  const tok1 = r.j.id;
  r = await call("POST", "/tokens/request", owner.tok, { unitId: uA.id });
  ok(r.s === 403, "owners cannot request tokens");
  r = await call("POST", "/tokens/request", t1.tok, { unitId: uA.id });
  ok(r.s === 409, "duplicate open request blocked");
  r = await call("POST", "/tokens/request", t2.tok, { unitId: uA.id });
  ok(r.s === 201, "tenant2 can also request the same unit (competing)");
  const tok2 = r.j.id;
  r = await call("GET", `/tokens/${tok1}`, t1.tok);
  ok(r.j.status === "REQUESTED" && r.j.pay === null && r.j.code === null, "before approval the tenant sees NO bank details");
  r = await call("GET", "/tokens/incoming", owner.tok);
  ok(r.j.length === 2 && r.j.every((t: any) => t.tenant.phone === undefined), "owner inbox shows requests without tenant phone yet");

  console.log("\n— APPROVAL");
  r = await call("POST", `/tokens/${tok1}/approve`, t1.tok);
  ok(r.s === 403, "tenant cannot approve");
  r = await call("POST", `/tokens/${tok1}/approve`, stranger.tok);
  ok(r.s === 404, "another owner cannot approve (cannot even see it)");
  await prisma.managerAssignment.updateMany({ where: { managerId: mgr.id }, data: { canApproveTokens: false } });
  r = await call("POST", `/tokens/${tok1}/approve`, mgr.tok);
  ok(r.s === 403, "manager without approve rights is refused");
  await prisma.managerAssignment.updateMany({ where: { managerId: mgr.id }, data: { canApproveTokens: true } });
  r = await call("POST", `/tokens/${tok1}/approve`, mgr.tok, { accountId: (await prisma.receivingAccount.findFirst({ where: { userId: mgr.id } }))!.id });
  ok(r.s === 400, "manager cannot use an account that isn't approved / allowed");
  r = await call("POST", `/tokens/${tok1}/approve`, mgr.tok);
  ok(r.s === 200 && /^HM-[A-Z2-9]{6}$/.test(r.j.code) && r.j.payTo.last4 === "6789", "manager approves; falls back to the OWNER's account; code issued");
  const code1 = r.j.code;
  ok((await prisma.unit.findUnique({ where: { id: uA.id } }))!.status === "RESERVED", "unit is RESERVED");
  r = await call("POST", `/tokens/${tok2}/approve`, owner.tok);
  ok(r.s === 409, "second applicant cannot be approved while the unit is held");
  r = await call("GET", `/tokens/${tok1}`, t1.tok);
  ok(r.j.status === "ACTIVE" && r.j.pay?.accountNumber === "0123456789" && r.j.pay.accountName === "OKAFOR CHINEDU" && r.j.pay.narration === code1, "tenant1 now sees the owner's full account details + code");
  r = await call("GET", `/tokens/${tok1}`, t2.tok);
  ok(r.s === 404, "tenant2 cannot open tenant1's token");
  r = await call("GET", `/tokens/${tok2}`, t2.tok);
  ok(r.j.pay === null, "tenant2 still sees no bank details");
  r = await call("GET", "/public/units?q=Unit%20A");
  ok(r.s === 200 && !JSON.stringify(r.j).includes(uA.id), "reserved unit disappears from public search");
  ok((await prisma.enquiry.count()) === 0 || true, "(enquiry sharing only applies if an enquiry exists)");
  const raw = (await prisma.paymentToken.findUnique({ where: { id: tok1 } }))!;
  ok(!!raw.payAccountNumberEnc && !raw.payAccountNumberEnc.includes("0123456789"), "account number is encrypted in the database");

  console.log("\n— PAYING AND CONFIRMING");
  let fd = new FormData();
  r = await call("POST", `/tokens/${tok1}/claim`, t1.tok, undefined, fd);
  ok(r.s === 400, "claim needs a receipt or a reference");
  r = await call("POST", `/tokens/${tok2}/claim`, t2.tok, undefined, (() => { const f = new FormData(); f.set("reference", "ABCD1234"); return f; })());
  ok(r.s === 409, "cannot claim payment on a token that was never approved");
  fd = new FormData(); fd.set("reference", "TRF-998877"); fd.set("file", new Blob([Buffer.from("%PDF-1.4 fake")], { type: "application/pdf" }), "proof.pdf");
  r = await call("POST", `/tokens/${tok1}/claim`, t1.tok, undefined, fd);
  ok(r.s === 200 && r.j.status === "PAYMENT_CLAIMED", "tenant claims payment with reference + receipt upload");
  r = await call("GET", `/tokens/${tok1}/proof`, owner.tok);
  ok(r.s === 200, "owner can open the proof of transfer");
  r = await call("GET", `/tokens/${tok1}/proof`, t2.tok);
  ok(r.s === 404, "another tenant cannot open it");
  r = await call("POST", `/tokens/${tok1}/cancel`, t1.tok);
  ok(r.s === 409, "tenant cannot cancel after claiming payment");
  r = await call("POST", `/tokens/${tok1}/revoke`, owner.tok, { reason: "changed my mind" });
  ok(r.s === 409, "owner cannot withdraw a token after payment was claimed");
  r = await call("GET", "/dashboard/staff", owner.tok);
  ok(r.j.paymentsToConfirm === 1 && r.j.pendingTokenRequests === 1, "owner dashboard counts: 1 to confirm, 1 pending request");
  r = await call("POST", `/tokens/${tok1}/confirm`, mgr.tok, { amountKobo: TOTAL });
  ok(r.s === 403, "manager whose account was NOT paid cannot confirm");
  r = await call("POST", `/tokens/${tok1}/confirm`, owner.tok, { amountKobo: TOTAL - 100 });
  ok(r.s === 400, "wrong amount is refused");
  r = await call("POST", `/tokens/${tok1}/confirm`, owner.tok, { amountKobo: TOTAL });
  ok(r.s === 200 && r.j.status === "PAID", "owner confirms the exact amount");
  r = await call("POST", `/tokens/${tok1}/confirm`, owner.tok, { amountKobo: TOTAL });
  ok(r.s === 409, "confirming twice is rejected (idempotent)");
  ok((await prisma.unit.findUnique({ where: { id: uA.id } }))!.status === "OCCUPIED", "unit is OCCUPIED");
  const ten = (await prisma.tenancy.findFirst({ where: { tokenId: tok1 } }))!;
  ok(!!ten && ten.tenantId === t1.id && Math.round((ten.endsAt.getTime() - ten.startsAt.getTime()) / DAY) >= 364, "tenancy created for 12 months");
  ok((await prisma.paymentToken.findUnique({ where: { id: tok2 } }))!.status === "CANCELLED", "competing request auto-cancelled");
  const tx = await prisma.transaction.findMany({ where: { tokenId: tok1 } });
  ok(tx.length === 1 && tx[0].channel === "BANK_TRANSFER" && tx[0].amountKobo === TOTAL && tx[0].status === "SUCCESS", "ledger row recorded as BANK_TRANSFER");
  r = await call("GET", `/tokens/${tok1}/receipt`, t1.tok);
  ok(r.s === 200 && r.buf!.subarray(0, 4).toString() === "%PDF", "receipt PDF generated");
  fs.writeFileSync("/tmp/receipt.pdf", r.buf!);
  r = await call("GET", `/tenancies/${ten.id}/agreement`, t1.tok);
  ok(r.s === 200 && r.buf!.subarray(0, 4).toString() === "%PDF", "agreement PDF generated");
  fs.writeFileSync("/tmp/agreement.pdf", r.buf!);
  ok(!!(await prisma.tenancy.findUnique({ where: { id: ten.id } }))!.agreementUrl, "agreement stored on the tenancy");
  r = await call("GET", `/tenancies/${ten.id}/agreement`, t2.tok);
  ok(r.s === 404, "other tenants cannot download the agreement");
  r = await call("GET", `/tokens/${tok1}`, t1.tok);
  ok(r.j.pay === null && r.j.status === "PAID", "after payment, the full account number is no longer exposed");
  r = await call("POST", `/tenancies/${ten.id}/confirm-move-in`, t1.tok);
  ok(r.s === 200, "tenant confirms move-in");

  console.log("\n— EXPIRY & LATE CLAIM");
  r = await call("POST", "/tokens/request", t2.tok, { unitId: uB.id }); const tokB = r.j.id;
  r = await call("POST", `/tokens/${tokB}/approve`, owner.tok, { hours: 6 });
  ok(r.s === 200, "approve unit B with 6h hold");
  await prisma.paymentToken.update({ where: { id: tokB }, data: { expiresAt: new Date(Date.now() - 1000) } });
  r = await call("GET", `/tokens/${tokB}`, t2.tok);
  ok(r.j.status === "EXPIRED" && r.j.pay === null, "past expiry the tenant view says EXPIRED and hides bank details (even before the job runs)");
  await runTokenJob();
  ok((await prisma.paymentToken.findUnique({ where: { id: tokB } }))!.status === "EXPIRED" && (await prisma.unit.findUnique({ where: { id: uB.id } }))!.status === "AVAILABLE", "job expires the token and re-lists the unit");
  fd = new FormData(); fd.set("reference", "LATE-TRF-1");
  r = await call("POST", `/tokens/${tokB}/claim`, t2.tok, undefined, fd);
  ok(r.s === 200 && r.j.status === "PAYMENT_CLAIMED" && (await prisma.unit.findUnique({ where: { id: uB.id } }))!.status === "RESERVED", "late claim (unit still free) re-holds the unit");
  r = await call("POST", `/tokens/${tokB}/not-received`, owner.tok, { note: "nothing in my account" });
  ok(r.j.status === "DISPUTED", "owner says not received → DISPUTED");
  r = await call("POST", `/tokens/${tokB}/confirm`, owner.tok, { amountKobo: TOTAL });
  ok(r.s === 200, "owner can still confirm later if the bank credit shows up");
  ok((await prisma.unit.findUnique({ where: { id: uB.id } }))!.status === "OCCUPIED", "unit B occupied after late confirmation");

  console.log("\n— LATE CLAIM AFTER UNIT TAKEN → DISPUTE → ADMIN");
  r = await call("POST", "/tokens/request", t1.tok, { unitId: uC.id }); const tokC = r.j.id;
  await call("POST", `/tokens/${tokC}/approve`, owner.tok);
  await prisma.paymentToken.update({ where: { id: tokC }, data: { expiresAt: new Date(Date.now() - 1000) } });
  await runTokenJob();
  r = await call("POST", "/tokens/request", t2.tok, { unitId: uC.id }); const tokC2 = r.j.id;
  await call("POST", `/tokens/${tokC2}/approve`, owner.tok); // someone else takes the hold
  fd = new FormData(); fd.set("reference", "LATE-TRF-2");
  r = await call("POST", `/tokens/${tokC}/claim`, t1.tok, undefined, fd);
  ok(r.j.status === "DISPUTED", "late claim when the unit is held by someone else → DISPUTED, not a silent loss");
  ok((await prisma.unit.findUnique({ where: { id: uC.id } }))!.status === "RESERVED", "the other tenant's hold is untouched");
  r = await call("GET", "/admin/tokens", adminTok);
  ok(r.j.length === 1 && r.j[0].id === tokC, "admin sees it in the dispute queue");
  r = await call("POST", `/admin/tokens/${tokC}/resolve`, adminTok, { outcome: "CONFIRM_PAID", notes: "check bank statement" });
  ok(r.s === 409, "admin cannot force-confirm when the unit is held by someone else");
  ok((await prisma.paymentToken.findUnique({ where: { id: tokC } }))!.status === "DISPUTED", "failed confirm rolled back cleanly: still DISPUTED");
  ok((await prisma.transaction.count({ where: { tokenId: tokC } })) === 0, "no ledger row from the failed attempt");
  r = await call("POST", `/admin/tokens/${tokC}/resolve`, adminTok, { outcome: "CANCEL", notes: "Unit rented to another applicant; owner to refund tenant directly" });
  ok(r.s === 200 && (await prisma.paymentToken.findUnique({ where: { id: tokC } }))!.status === "CANCELLED", "admin cancels the dispute");
  ok((await prisma.unit.findUnique({ where: { id: uC.id } }))!.status === "RESERVED", "cancelling a lapsed token does NOT free someone else's hold");
  r = await call("POST", `/tokens/${tokC2}/revoke`, owner.tok, { reason: "testing" });
  ok(r.s === 200 && (await prisma.unit.findUnique({ where: { id: uC.id } }))!.status === "AVAILABLE", "owner withdraws an unpaid token: unit released");

  console.log("\n— SILENT RECEIVER ESCALATION");
  r = await call("POST", "/tokens/request", t2.tok, { unitId: uD.id }); const tokD = r.j.id;
  await call("POST", `/tokens/${tokD}/approve`, owner.tok);
  fd = new FormData(); fd.set("reference", "TRF-D-1"); await call("POST", `/tokens/${tokD}/claim`, t2.tok, undefined, fd);
  r = await call("POST", `/tokens/${tokD}/dispute`, t2.tok, { reason: "owner not answering" });
  ok(r.s === 400, "tenant must wait 24h before disputing");
  await prisma.paymentToken.update({ where: { id: tokD }, data: { claimedAt: new Date(Date.now() - 49 * 3600_000) } });
  await runTokenJob();
  ok((await prisma.paymentToken.findUnique({ where: { id: tokD } }))!.status === "DISPUTED", "48h of silence escalates to DISPUTED automatically");
  ok((await prisma.notification.count({ where: { userId: admin.id, type: "DISPUTE" } })) >= 2, "admins were notified");
  r = await call("POST", `/admin/tokens/${tokD}/resolve`, adminTok, { outcome: "CONFIRM_PAID", notes: "Bank statement seen" });
  ok(r.s === 200 && (await prisma.unit.findUnique({ where: { id: uD.id } }))!.status === "OCCUPIED", "admin confirms after reviewing evidence; unit occupied");

  console.log("\n— RENEWAL");
  await prisma.tenancy.update({ where: { id: ten.id }, data: { endsAt: new Date(Date.now() + 20 * DAY) } });
  r = await call("POST", "/tokens/renew", t2.tok, { tenancyId: ten.id });
  ok(r.s === 404, "other tenants cannot renew someone else's tenancy");
  r = await call("POST", "/tokens/renew", t1.tok, { tenancyId: ten.id });
  ok(r.s === 201 && r.j.totalKobo === 52_000_00, "renewal total = rent + service charge (no new caution)");
  const tokR = r.j.id;
  r = await call("POST", `/tokens/${tokR}/approve`, owner.tok);
  ok(r.s === 200 && (await prisma.unit.findUnique({ where: { id: uA.id } }))!.status === "OCCUPIED", "renewal approved; unit stays OCCUPIED");
  fd = new FormData(); fd.set("reference", "TRF-RENEW"); await call("POST", `/tokens/${tokR}/claim`, t1.tok, undefined, fd);
  const before = (await prisma.tenancy.findUnique({ where: { id: ten.id } }))!.endsAt;
  r = await call("POST", `/tokens/${tokR}/confirm`, owner.tok, { amountKobo: 52_000_00 });
  const after = (await prisma.tenancy.findUnique({ where: { id: ten.id } }))!;
  ok(r.s === 200 && Math.round((after.endsAt.getTime() - before.getTime()) / DAY) >= 364 && after.renewedCount === 1, "renewal extends the END date by 12 months (no days lost)");

  console.log("\n— REMINDERS & ENDING");
  await prisma.tenancy.update({ where: { id: ten.id }, data: { endsAt: new Date(Date.now() + 5 * DAY) } });
  await runTokenJob(); await runTokenJob();
  ok((await prisma.notification.count({ where: { userId: t1.id, type: { startsWith: "RENT_7D" } } })) === 1, "7-day reminder sent exactly once across two job runs");
  r = await call("POST", `/tenancies/${ten.id}/end`, owner.tok, { relist: true });
  ok(r.s === 200 && r.j.unitStatus === "AVAILABLE", "owner ends the tenancy and relists");
  r = await call("GET", "/tenancies/mine", t1.tok);
  ok(r.s === 200 && r.j.length === 1 && r.j[0].active === false, "tenant sees the ended tenancy");

  console.log(`\n${pass} passed, ${fail} failed`);
  process.exit(fail ? 1 : 0);
}
main().catch((e) => { console.error(e); process.exit(1); });
