import PDFDocument from "pdfkit";
import fs from "fs";
import { prisma } from "./prisma";
import { writePrivate, readPrivate } from "./storage";
import { decrypt } from "./crypto";

// pdfkit's built-in fonts have no ₦ glyph, so PDFs say "NGN".
const ngn = (n: number) => "NGN " + n.toLocaleString("en-NG", { maximumFractionDigits: 0 });
const day = (d: Date) => d.toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" });
const PERIOD = { MONTHLY: "month", QUARTERLY: "quarter (3 months)", BIANNUAL: "6 months", ANNUAL: "year" } as const;

function render(build: (d: PDFKit.PDFDocument) => void): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const d = new PDFDocument({ size: "A4", margin: 56 }), chunks: Buffer[] = [];
    d.on("data", (c) => chunks.push(c)); d.on("end", () => resolve(Buffer.concat(chunks))); d.on("error", reject);
    build(d); d.end();
  });
}
const row = (d: PDFKit.PDFDocument, k: string, v: string) => { // fixed two-column layout so long values never wrap under the label
  const y = d.y;
  d.font("Helvetica").fontSize(10).fillColor("#555").text(k, 56, y, { width: 170 }); const y1 = d.y;
  d.font("Helvetica-Bold").fillColor("#000").text(v, 230, y, { width: 310 }); d.y = Math.max(y1, d.y) + 3; d.x = 56;
};

async function load(tenancyId: string) {
  const t = await prisma.tenancy.findUnique({ where: { id: tenancyId }, include: {
    tenant: { select: { fullName: true, email: true, phone: true } },
    unit: { include: { property: { include: { location: { select: { name: true } }, owner: { select: { fullName: true, phone: true, email: true } }, parent: { select: { name: true } } } } } } } });
  if (!t) return null;
  const token = t.tokenId ? await prisma.paymentToken.findUnique({ where: { id: t.tokenId } }) : null;
  const confirmer = token?.confirmedById ? await prisma.user.findUnique({ where: { id: token.confirmedById }, select: { fullName: true } }) : null;
  return { t, token, confirmer };
}

export async function agreementBuffer(tenancyId: string) {
  const x = await load(tenancyId); if (!x) return null;
  const { t, token, confirmer } = x, p = t.unit.property, total = token ? token.rentNaira + token.cautionNaira + token.serviceChargeNaira : t.rentNaira;
  return render((d) => {
    d.font("Helvetica-Bold").fontSize(18).text("TENANCY AGREEMENT", { align: "center" }).moveDown(0.3);
    d.font("Helvetica").fontSize(9).fillColor("#666").text("Generated by the platform from the confirmed rental. Reference " + (token?.code ?? t.id), { align: "center" }).moveDown(1.2);
    d.fillColor("#000").font("Helvetica-Bold").fontSize(12).text("1. Parties").moveDown(0.3);
    row(d, "Landlord:", p.owner.fullName); row(d, "Tenant:", t.tenant.fullName);
    d.moveDown(0.8).font("Helvetica-Bold").fontSize(12).text("2. The premises").moveDown(0.3);
    row(d, "Unit:", t.unit.title); row(d, "Property:", p.name + (p.parent ? " (" + p.parent.name + ")" : "")); row(d, "Address:", `${p.address}, ${p.location.name}`);
    d.moveDown(0.8).font("Helvetica-Bold").fontSize(12).text("3. Term and rent").moveDown(0.3);
    row(d, "Starts:", day(t.startsAt)); row(d, "Ends:", day(t.endsAt));
    row(d, "Rent:", `${ngn(t.rentNaira)} per ${PERIOD[t.payDuration]}`);
    if (token) { row(d, "Caution (security) deposit:", ngn(token.cautionNaira)); row(d, "Service charge:", ngn(token.serviceChargeNaira)); }
    row(d, "Total paid on signing:", ngn(total));
    d.moveDown(0.8).font("Helvetica-Bold").fontSize(12).text("4. Payment").moveDown(0.3);
    d.font("Helvetica").fontSize(10).text(token
      ? `The tenant paid ${ngn(total)} by bank transfer directly to ${token.payAccountName} (${token.payBankName}, account ending ${token.payAccountNumberEnc ? decrypt(token.payAccountNumberEnc).slice(-4) : "----"}). Receipt of this payment was confirmed on the platform by ${confirmer?.fullName ?? "the landlord's representative"} on ${token.confirmedAt ? day(token.confirmedAt) : "-"}. The platform did not receive or hold any of this money.`
      : "Payment details are recorded on the platform.");
    d.moveDown(0.8).font("Helvetica-Bold").fontSize(12).text("5. Terms").moveDown(0.3);
    d.font("Helvetica").fontSize(10).list([
      "The tenant will use the premises as a residence (or the agreed use) and will not sublet without the landlord's written consent.",
      "The tenant will pay rent on or before the due date and keep the premises in good condition, fair wear and tear excepted.",
      "The caution deposit is held by the landlord and returned at the end of the tenancy after deducting only proven damage or unpaid sums.",
      "Repairs and faults are reported through the platform's maintenance tickets so both sides have a record.",
      "Either party must give notice before the tenancy ends or is not renewed, as required by the tenancy law of the state where the premises are located.",
      "Any rent increase or change to these terms must be agreed in writing by both parties.",
    ], { bulletRadius: 1.5, textIndent: 10 });
    d.moveDown(1.2).font("Helvetica-Oblique").fontSize(8.5).fillColor("#666").text("This is a standard summary agreement generated by the platform. The parties may agree additional written terms. It is not legal advice.");
  });
}

export async function receiptBuffer(tokenId: string) {
  const t = await prisma.paymentToken.findUnique({ where: { id: tokenId }, include: {
    tenant: { select: { fullName: true } }, unit: { include: { property: { include: { owner: { select: { fullName: true } } } } } } } });
  if (!t || t.status !== "PAID") return null;
  const total = t.rentNaira + t.cautionNaira + t.serviceChargeNaira + t.platformFeeNaira;
  const logo = await logoOf(t.unit.property.ownerId);
  return render((d) => {
    if (logo) drawLogo(d, logo);
    d.font("Helvetica-Bold").fontSize(18).text("PAYMENT RECEIPT", { align: "center" }).moveDown(1);
    row(d, "Receipt no:", t.code ?? t.id); row(d, "Date confirmed:", t.confirmedAt ? day(t.confirmedAt) : "-");
    row(d, "Received from:", t.tenant.fullName); row(d, "Landlord:", t.unit.property.owner.fullName);
    row(d, "For:", (t.kind === "RENEWAL" ? "Renewal of " : "") + t.unit.title);
    d.moveDown(0.8);
    row(d, "Rent:", ngn(t.rentNaira)); if (t.cautionNaira) row(d, "Caution deposit:", ngn(t.cautionNaira)); if (t.serviceChargeNaira) row(d, "Service charge:", ngn(t.serviceChargeNaira));
    d.moveDown(0.4); row(d, "TOTAL:", ngn(total));
    d.moveDown(0.8); row(d, "Paid to:", `${t.payAccountName} (${t.payBankName})`); row(d, "Method:", "Bank transfer, paid directly to the landlord or manager");
    d.moveDown(1.2).font("Helvetica-Oblique").fontSize(8.5).fillColor("#666").text("Receipt of this payment was confirmed on the platform by the person who received it. The platform does not hold or process rent.");
  });
}

// Saved once at confirmation so the agreement is a fixed record; regenerated on demand if the file is ever missing.
export async function writeAgreement(tenancyId: string) {
  const buf = await agreementBuffer(tenancyId); if (!buf) return null;
  const key = `agreement-${tenancyId}.pdf`;
  await writePrivate(key, buf);
  await prisma.tenancy.update({ where: { id: tenancyId }, data: { agreementUrl: key } });
  return buf;
}

// ───── Landlord-issued agreements and logo ─────
export const AGREEMENT_FIELDS = ["tenant_name", "tenant_email", "tenant_phone", "landlord_name", "landlord_phone", "property_name", "unit_title", "address", "rent", "caution", "service_charge", "total", "pay_period", "start_date", "end_date", "receipt_no", "today"];
const isImg = (k?: string | null) => !!k && /\.(png|jpg)$/.test(k);
/** The owner's logo for receipts: default template first, else the newest template that has one. */
export async function logoOf(ownerId: string) {
  const t = await prisma.agreementTemplate.findFirst({ where: { ownerId, active: true, logoKey: { not: null } }, orderBy: [{ isDefault: "desc" }, { updatedAt: "desc" }] });
  return t && isImg(t.logoKey) ? readPrivate(t.logoKey!) : null;
}
function drawLogo(d: PDFKit.PDFDocument, buf: Buffer) {
  try { d.image(buf, 56, 40, { fit: [140, 60] }); d.y = 110; d.x = 56; } catch { /* unreadable image: skip the logo */ }
}
const fill = (s: string, v: Record<string, string>) => s.replace(/\{\{\s*(\w+)\s*\}\}/g, (m, k) => v[k] ?? m).replace(/₦/g, "NGN ");
function agreementPdf(body: string, v: Record<string, string>, logo: Buffer | null) {
  return render((d) => {
    if (logo) drawLogo(d, logo);
    for (const raw of fill(body, v).split(/\r?\n/)) {
      const line = raw.trim();
      if (!line) { d.moveDown(0.4); continue; }
      if (line.startsWith("# ")) d.moveDown(0.3).font("Helvetica-Bold").fontSize(12).fillColor("#000").text(line.slice(2)).moveDown(0.2);
      else d.font("Helvetica").fontSize(10.5).fillColor("#000").text(line, { align: "justify" }).moveDown(0.3);
    }
    if (d.y > 640) d.addPage();
    const y = d.y + 40;
    d.font("Helvetica").fontSize(10).text("______________________", 56, y).text(v.landlord_name + " (Landlord)", 56, y + 14);
    d.text("______________________", 320, y).text(v.tenant_name + " (Tenant)", 320, y + 14);
    d.fontSize(8).fillColor("#777").text("Issued through Direct Homes. Ref " + v.receipt_no, 56, y + 50);
  });
}
type Tpl = { body: string; logoKey: string | null };
async function tplLogo(tpl: Tpl, ownerId: string) { return isImg(tpl.logoKey) ? readPrivate(tpl.logoKey!) : logoOf(ownerId); }
export async function issueAgreement(tenancyId: string, tpl: Tpl) {
  const x = await load(tenancyId); if (!x) return null;
  const { t, token } = x, p = t.unit.property, total = token ? token.rentNaira + token.cautionNaira + token.serviceChargeNaira : t.rentNaira;
  const v: Record<string, string> = { tenant_name: t.tenant.fullName, tenant_email: t.tenant.email, tenant_phone: t.tenant.phone, landlord_name: p.owner.fullName, landlord_phone: p.owner.phone, property_name: p.name + (p.parent ? ` (${p.parent.name})` : ""), unit_title: t.unit.title, address: `${p.address}, ${p.location.name}`, rent: ngn(t.rentNaira), caution: ngn(token?.cautionNaira ?? 0), service_charge: ngn(token?.serviceChargeNaira ?? 0), total: ngn(total), pay_period: PERIOD[t.payDuration], start_date: day(t.startsAt), end_date: day(t.endsAt), receipt_no: token?.code ?? t.id, today: day(new Date()) };
  const buf = await agreementPdf(tpl.body, v, await tplLogo(tpl, p.ownerId)), key = `agreement-${tenancyId}.pdf`;
  await writePrivate(key, buf);
  await prisma.tenancy.update({ where: { id: tenancyId }, data: { agreementUrl: key } });
  return buf;
}
export async function previewAgreement(tpl: Tpl, ownerId: string, ownerName: string) {
  const v: Record<string, string> = { tenant_name: "Chinedu Okafor", tenant_email: "chinedu@example.com", tenant_phone: "08012345678", landlord_name: ownerName, landlord_phone: "08000000000", property_name: "Sample Court", unit_title: "2-bedroom flat, Block B", address: "12 Sample Street, Lekki", rent: ngn(180000000), caution: ngn(20000000), service_charge: ngn(10000000), total: ngn(210000000), pay_period: "year", start_date: day(new Date()), end_date: day(new Date(Date.now() + 365 * 86_400_000)), receipt_no: "SAMPLE-0001", today: day(new Date()) };
  return agreementPdf(tpl.body, v, await tplLogo(tpl, ownerId));
}
